### PR TITLE
Introduce MSG_CURSOR (VM to GUI)

### PR DESCRIPTION
**Pull request by pwmarcz**
See QubesOS/qubes-issues#1551.

The message contains a cursor ID to be set for a given window.

### CODE REVIEW

**Comment by pwmarcz** [comment]
I'm not too happy with `CURSOR_EMPTY = 0x10000`, but I'd rather retain the original cursor IDs (which start from 0) instead of complicating the scheme by encoding them.

**Comment by marmarek** [comment]
In fact I think CURSOR_EMPTY is a risky thing to allow by default (if it does what I think it does - hides the cursor). It could be used to fool the user about the mouse position, potentially convincing the user to click on a specific thing outside of the VM's window.
This should be guarded by some extra option, maybe the same as allowing VM-initiated fullscreen window?

**Comment by pwmarcz** [comment]
Sorry, it's `CURSOR_NONE`, not empty, and it means delete the custom cursor and use default (named so because Xlib actually calls this `None`). No invisible cursor.

**Comment by pwmarcz** [comment]
One alternative would be to specify this default as 0, and shift the rest of cursor IDs (encode them as `x + 1`, or `x | 0x100`, or something).

**Comment by marmarek** [comment]
0 would be logical for "revert to default" indeed. I slightly more like `x | 0x100` for encoding others (name it `0x100` bit means X11 cursor codes).

**Comment by pwmarcz** [comment]
Updated and tested (and I renamed the default one to `CURSOR_DEFAULT`). That does look nice.

**Review by marmarek — APPROVED** [review]

**Pull request merged**
