### PR TITLE
Document changes in v1.6

### PR DESCRIPTION
**Pull request by DemiMarie**
This only adds one enum variant and bumps the version.

### CODE REVIEW

**Review by marmarek — APPROVED** [review]
This looks okay, but I'll merge it only after no-data MSG_WINDOW_DUMP_ACK is proven (via working implementation in agent/daemon) to be enough.

**Comment by DemiMarie** [comment]
@marmarek The agent and daemon need a definition of `MSG_WINDOW_DUMP_ACK` in order to compile.  Should they include their own definition?  Blocking on this PR being merged creates a circular dependency I would prefer to avoid.

**Comment by marmarek** [comment]
You can sure compile and test it locally. The CI for related daemon/agent PRs will fail before merging this one, but that isn't a problem. And BTW, the machinery for openqa builds can build multiple PRs depending on each other, so that isn't an issue either.

**Comment by DemiMarie** [comment]
PipelineRetryFailed

**Review by marmarek — APPROVED** [review]

**Pull request merged**
